{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.serviceAccount.name }}
    {{- if .Values.podIdentity.azureWorkload.enabled }}
    azure.workload.identity/use: {{ .Values.podIdentity.azureWorkload.enabled | quote }}
    {{- end }}
    {{- include "keda.labels" . | indent 4 }}
  {{- if or .Values.podIdentity.azureWorkload.enabled .Values.serviceAccount.annotations }}
  annotations:
    {{- if .Values.podIdentity.azureWorkload.enabled }}
    azure.workload.identity/client-id: {{ .Values.podIdentity.azureWorkload.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.podIdentity.azureWorkload.tenantId | quote }}
    azure.workload.identity/service-account-token-expiration: {{ .Values.podIdentity.azureWorkload.tokenExpiration | quote }}
    {{- end }}
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4}}
    {{- end }}
  {{- end }}
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
