apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if and .Values.prometheus.operator.enabled ( not (or .Values.prometheus.operator.podMonitor.enabled .Values.prometheus.operator.serviceMonitor.enabled )) }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.prometheus.operator.port | quote }}
    prometheus.io/path: "/metrics"
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    {{- include "keda.labels" . | indent 4 }}
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metricsservice
    port: 9666
    targetPort: 9666
  {{- if .Values.prometheus.operator.enabled }}
  - name: metrics
    port: {{ .Values.prometheus.operator.port }}
    targetPort: {{ .Values.prometheus.operator.port }}
  {{- end }}
  selector:
    app: {{ .Values.operator.name }}
