{{- if .Values.podDisruptionBudget.operator }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.operator.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceAccount.name }}
    {{- include "keda.labels" . | indent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.operator.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.operator.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.operator.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.operator.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.operator.name }}
{{- end }}
