apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.operatorName }}-metrics-apiserver
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Values.operatorName }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.operatorName }}-metrics-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.portHttps }}
    targetPort: {{ .Values.service.portHttpsTarget }}
    protocol: TCP
  - name: http
    port: {{ .Values.service.portHttp }}
    targetPort: {{ .Values.service.portHttpTarget }}
    protocol: TCP
  selector:
    app: {{ .Values.operatorName }}-metrics-apiserver
