apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.operatorName }}-metrics-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.portHttps }}
    targetPort: {{ .Values.service.portHttpsTarget }}
    protocol: TCP
  - name: http
    port: {{ .Values.service.portHttp }}
    targetPort: {{ .Values.service.portHttpTarget }}
    protocol: TCP
  selector:
    app: {{ .Values.operatorName }}-metrics-apiserver
