apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app.kubernetes.io/name: v1beta1.external.metrics.k8s.io
    {{- include "keda.labels" . | indent 4 }}
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: {{ .Values.operator.name }}-metrics-apiserver
    namespace: {{ .Release.Namespace }}
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
