{{- if and .Values.prometheus.metricServer.enabled .Values.prometheus.metricServer.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.operator.name }}-metrics-apiserver
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    {{- include "keda.labels" . | indent 4 }}
    {{- range $key, $value := .Values.prometheus.metricServer.podMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.prometheus.metricServer.podMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  podMetricsEndpoints:
  - port: metrics
    path: {{ .Values.prometheus.metricServer.path }}
    honorLabels: true
    {{- with .Values.prometheus.metricServer.podMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.metricServer.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Values.operator.name }}-metrics-apiserver
{{- end }}
