apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ .Values.operator.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.operator.portHttp }}
    targetPort: {{ .Values.service.operator.portHttpTarget }}
    protocol: TCP
  selector:
    app: {{ .Values.operator.name }}
