apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.webhooks.name }}
    {{- include "keda.labels" . | indent 4 }}
  name: {{ .Values.webhooks.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 9443
  {{- if .Values.prometheus.webhooks.enabled }}
  - name: metrics
    port: {{ .Values.prometheus.webhooks.port }}
    targetPort: {{ .Values.prometheus.webhooks.port }}
  {{- end }}
  selector:
    app: {{ .Values.webhooks.name }}
