{{- if and .Values.certificates.certManager.enabled .Values.certificates.certManager.generateCA }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.operator.name }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .Values.operator.name }}
  secretName: {{ .Values.certificates.certManager.caSecretName }}
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 8760h # 1 year
  renewBefore: 5840h # 8 months
  issuerRef:
    name: {{ .Values.operator.name }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
{{- end }}