{{- if .Values.certificates.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    {{- toYaml .Values.additionalAnnotations | nindent 4 }}
  name: {{ .Values.operator.name }}-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ .Values.certificates.certManager.caSecretName }}
{{- end }}