{{- if .Values.agent.rbac.create }}
{{- if .Values.agent.rbac.shouldBeAbleToInstallKeda }}
# Following rbac is needed for kedify agent to be able to install also the KEDA
# most of these rules are not used by kedify agent itself, but its service account still needs them assigned
# to be able to create install the KEDA and its RBAC (privilege escalation feature of k8s rbac).

# If you find these rbac rules too permissive, consider installing KEDA on your own and use Kedify in Adopt mode
# this way keda-installer role will not be required by Kedify.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keda-installer
  {{ .Release.Namespace }}
  labels:
    control-plane: kedify-agent
rules:

# When installing keda create its rbac
# serviceaccounts
- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs:
    - '*'
  resourceNames:
    - keda-operator
    - keda-metrics-server
    - keda-webhook
- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs:
    - create

# roles
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - roles
  verbs:
    - delete
    - get
    - patch
    - update
  resourceNames:
    - keda-operator-certs
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - roles
  verbs:
    - create

# rolebindings
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
  verbs:
    - delete
    - get
    - patch
    - update
  resourceNames:
    - keda-operator-certs
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
  verbs:
    - create

# When installing keda create certain Services and Deployments
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - '*'
  resourceNames:
    - keda-operator
    - keda-operator-metrics-apiserver
    - keda-admission-webhooks
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - create
- apiGroups:
    - "apps"
  resources:
    - deployments
  verbs:
    - '*'
  resourceNames:
    - keda-operator
    - keda-operator-metrics-apiserver
    - keda-admission-webhooks
- apiGroups:
    - "apps"
  resources:
    - deployments
  verbs:
    - create

# keda-operator-certs
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
  resourceNames:
    - "kedaorg-certs"
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-installer
  {{ .Release.Namespace }}
  labels:
    control-plane: kedify-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-installer
subjects:
  - kind: ServiceAccount
    name: kedify-agent
    {{ .Release.Namespace }}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-installer
rules:

# we need to have the same rules to prevent privilege escalation issue - https://kubernetes.io/docs/reference/access-authn-authz/rbac/#restrictions-on-role-binding-creation-or-update

# rolebindings (crud keda-operator rolebinding cluster-wide, used when keda's watchNamespace property is not empty)
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
  verbs:
    - delete
    - get
    - patch
    - update
  resourceNames:
    - keda-operator
    - keda-operator-auth-reader
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
  verbs:
    - create

  # clusterroles
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles
  verbs:
    - delete
    - get
    - patch
    - update
  resourceNames:
    - keda-operator-minimal-cluster-role
    - keda-operator
    - keda-operator-external-metrics-reader
    - keda-operator-webhook
    - kedify-keda-operator-http-admin

- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles
  verbs:
    - create

  # clusterrolebindings
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
  verbs:
    - delete
    - get
    - patch
    - update
  resourceNames:
    - keda-operator-minimal
    - keda-operator
    - keda-operator-webhook
    - keda-operator-system-auth-delegator
    - keda-operator-hpa-controller-external-metrics
    - kedify-keda-operator-http-admin
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterrolebindings
  verbs:
    - create

# additional content of keda-operator-minimal cluster role
- apiGroups:
    - apiregistration.k8s.io
  resources:
    - apiservices
  verbs:
    - get
    - list
    - patch
    - update
    - watch

# additional content of keda-operator-external-metrics-reader cluster role
- apiGroups:
    - external.metrics.k8s.io
  resources:
    - '*'
  verbs:
    - '*'

# additional content of keda-operator cluster role
- apiGroups:
    - ""
  resources:
    - configmaps
    - configmaps/status
    - limitranges
    - pods
    - services
    - serviceaccounts
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - list
    - watch
- apiGroups:
    - "*"
  resources:
    - "*/scale"
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - "*"
  resources:
    - "*"
  verbs:
    - get
- apiGroups:
    - apps
  resources:
    - deployments/scale
    - statefulsets/scale
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
    - statefulsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - '*'
- apiGroups:
    - batch
  resources:
    - jobs
  verbs:
    - '*'
- apiGroups:
    - eventing.keda.sh
  resources:
    - cloudeventsources
    - cloudeventsources/status
  verbs:
    - '*'
- apiGroups:
    - keda.sh
  resources:
    - scaledjobs
    - scaledjobs/finalizers
    - scaledjobs/status
    - scaledobjects
    - scaledobjects/finalizers
    - scaledobjects/status
    - triggerauthentications
    - triggerauthentications/status
  verbs:
    - '*'

# for registering the keda's validating webhook called 'keda-admission'
- apiGroups:
    - admissionregistration.k8s.io
  resources:
    - validatingwebhookconfigurations
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-installer
subjects:
  - kind: ServiceAccount
    name: kedify-agent
    {{ .Release.Namespace }}
{{- end }}
{{- end }}
