apiVersion: v1
kind: ServiceAccount
metadata:
  name: kedify-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kedify-agent.labels" . | nindent 4 }}
  {{- with .Values.agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.agent.serviceAccount.automount }}
