{{- if and .Values.certificates.certManager.enabled .Values.certificates.certManager.issuer.generate }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.operator.name }}-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keda.labels" . | indent 4 }}
spec:
  ca:
    secretName: {{ .Values.certificates.certManager.caSecretName }}
{{- end }}
