{{- if and .Values.certificates.certManager.enabled (not .Values.certificates.certManager.existingIssuer.enabled) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    {{- toYaml .Values.additionalAnnotations | nindent 4 }}
  name: {{ .Values.operator.name }}-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
