{{- if .Values.certificates.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.operator.name }}-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ .Values.certificates.certManager.caSecretName }}
{{- end }}