apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: interceptor-proxy
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: "{{ .Chart.Name }}-{{ .Values.interceptor.proxy.service }}"
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: proxy
    port: {{ default 9091 .Values.interceptor.proxy.port }}
    targetPort: proxy
  selector:
    app.kubernetes.io/component: interceptor
    {{- include "keda-http-add-on.matchLabels" . | indent 4 }}
