apiVersion: v1
kind: Service
metadata:
  labels:    
    app.kubernetes.io/component: interceptor-admin
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: "{{ .Chart.Name }}-{{ .Values.interceptor.admin.service }}"
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: admin
    port: {{ default 9091 .Values.interceptor.admin.port }}
    targetPort: admin
  selector:
    app.kubernetes.io/component: interceptor
    {{- include "keda-http-add-on.matchLabels" . | indent 4 }}
