apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: interceptor
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-interceptor
  namespace: {{ .Release.Namespace }}
