apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: operator
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
