{{- if gt (int .Values.operator.replicas) 0 }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: http-add-on
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
