# this is the ScaledObject that tells KEDA to scale the interceptor fleet
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{{ .Chart.Name }}-interceptor"
  namespace: {{ .Release.Namespace }}
spec:
  minReplicaCount: {{ .Values.interceptor.replicas.min }}
  maxReplicaCount: {{ .Values.interceptor.replicas.max }}
  pollingInterval: {{ .Values.interceptor.scaledObject.pollingInterval }}
  scaleTargetRef:
    name: "{{ .Chart.Name }}-interceptor"
    kind: Deployment
  triggers:
    - type: external
      metadata:
        scalerAddress: "{{ .Chart.Name }}-{{ .Values.scaler.service }}:{{ default 9091 .Values.scaler.grpcPort }}"
        interceptorTargetPendingRequests: "{{ default 200 .Values.scaler.pendingRequestsInterceptor }}"
