apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmosdb-scaler.labels" . | indent 4 }}
spec:
  ports:
    - name: grpc
      port: {{ .Values.port | default 4050 }}
      targetPort: scaler-grpc
  selector:
    app: {{ .Chart.Name }}