apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-external-scaler
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - http.keda.sh
  resources:
  - httpscaledobjects
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    httpscaledobjects.http.keda.sh/version: {{ .Values.images.tag | default .Chart.AppVersion }}
    keda.sh/addon: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    name: {{ .Chart.Name }}-external-scaler
    app.kubernetes.io/name: {{ .Chart.Name }}-external-scaler
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-external-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-external-scaler
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-external-scaler
  namespace: {{ .Release.Namespace }}
