apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: scaler
    app.kubernetes.io/name: http-add-on
    {{- include "keda-http-add-on.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-external-scaler
  namespace: {{ .Release.Namespace }}
