{{- if (.Values.serviceAccount.webhooks).create | default .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ (.Values.serviceAccount.webhooks).name | default .Values.serviceAccount.name }}
    {{- include "keda.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.additionalAnnotations }}
    {{- toYaml .Values.additionalAnnotations | nindent 4 }}
    {{- end }}
    {{- if (.Values.serviceAccount.webhooks).annotations | default .Values.serviceAccount.annotations }}
    {{- toYaml ((.Values.serviceAccount.webhooks).annotations | default .Values.serviceAccount.annotations) | nindent 4}}
    {{- end }}
  name: {{ (.Values.serviceAccount.webhooks).name | default .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ (.Values.serviceAccount.webhooks).automountServiceAccountToken | default .Values.serviceAccount.automountServiceAccountToken }}
{{- end -}}
