{{- if and .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- if and .Values.prometheus.webhooks.enabled ( not .Values.prometheus.webhooks.serviceMonitor.enabled ) }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.prometheus.webhooks.port | quote }}
    prometheus.io/path: "/metrics"
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.webhooks.name }}
    {{- include "keda.labels" . | nindent 4 }}
  name: {{ .Values.webhooks.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 9443
  {{- if .Values.prometheus.webhooks.enabled }}
  - name: {{ .Values.prometheus.webhooks.serviceMonitor.port }}
    port: {{ .Values.prometheus.webhooks.port }}
    targetPort: {{ .Values.prometheus.webhooks.port }}
  {{- end }}
  selector:
    app: {{ .Values.webhooks.name }}
{{- end }}
