apiVersion: v2
type: application
name: keda-add-ons-http
description: Event-based autoscaler for HTTP workloads on Kubernetes

# Specify the Kubernetes version range that we support.
# We allow pre-release versions for cloud-specific Kubernetes versions such as  v1.21.5-gke.1302 or v1.18.9-eks-d1db3c
kubeVersion: ">=v1.23.0-0"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version. This is incremented at chart release time and does not need
# to be included in any PRs to main.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.7.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 0.7.0
home: https://github.com/kedacore/http-add-on
sources:
  - https://github.com/kedacore/http-add-on
maintainers:
  - name: Ahmed ElSayed
    email: ahmels@microsoft.com
  - name: Jorge Turrado
    email: jorge_turrado@hotmail.es
  - name: Tom Kerkhove
    email: kerkhove.tom@gmail.com
  - name: Zbynek Roubalik
    email: zbynek@kedify.io
