apiVersion: v2
name: keda-add-ons-http
description: Event-based autoscaler for HTTP workloads on Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 0.0.1
home: https://github.com/kedacore/http-add-on
sources:
  - https://github.com/kedacore/http-add-on
maintainers:
  - name: Ahmed ElSayed
    email: ahmels@microsoft.com
  - name: Tom Kerkhove
    email: kerkhove.tom@gmail.com
  - name: Zbynek Roubalik
    email: zroubali@redhat.com
  - name: Lucas Santos
    email: ludossan@microsoft.com
  - name: Aaron Schlesinger
    email: aaron.schlesinger@microsoft.com
