{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}-external-metrics-reader
    {{- include "keda.labels" . | indent 4 }}
  name: {{ .Values.operator.name }}-external-metrics-reader
rules:
- apiGroups:
  - external.metrics.k8s.io
  resources:
  - 'externalmetrics'
  verbs:
  - 'get'
{{- end -}}
