{{- if and .Values.prometheus.metricServer.enabled .Values.prometheus.metricServer.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.operator.name }}-metrics-apiserver
  annotations:
    {{- toYaml .Values.additionalAnnotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    {{- include "keda.labels" . | indent 4 }}
    {{- range $key, $value := .Values.prometheus.metricServer.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.prometheus.metricServer.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  {{- with .Values.prometheus.metricServer.serviceMonitor.jobLabel }}
  jobLabel: {{ . }}
  {{- end }}
  {{- with .Values.prometheus.metricServer.serviceMonitor.targetLabels }}
  targetLabels:
  {{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.prometheus.metricServer.serviceMonitor.podTargetLabels }}
  podTargetLabels:
  {{ toYaml . | indent 4 }}
  {{- end }}
  endpoints:
  - port: {{ .Values.prometheus.metricServer.portName }}
    {{- with .Values.prometheus.metricServer.serviceMonitor.targetPort }}
    targetPort: {{ . }}
    {{- end }}
    path: {{ .Values.prometheus.metricServer.path }}
    {{- with .Values.prometheus.metricServer.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.metricServer.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.metricServer.serviceMonitor.relabellings }}
    relabelings:
    {{ toYaml . | indent 6 }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.operator.name }}-metrics-apiserver
{{- end }}
