{{- if .Values.agent.createKedifyConfiguration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-kedifyconfig
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    helm.sh/hook-weight: "-2"
data:
  content: |
    apiVersion: install.kedify.io/v1alpha1
    kind: KedifyConfiguration
    metadata:
      name: kedify
      namespace: {{ .Release.Namespace }}
    spec:
      clusterName: {{ .Values.clusterName }}
      kedaInstallations:
      - agentAutoUpdate: false
        httpAddonHelm:
          enabled: true
          values: |-
            ---
        kedaHelm:
          enabled: true
          values: |-
            ---
        mode: Disabled
        name: keda
        namespace: {{ .Release.Namespace }}
        telemetry:
          controlPlane:
            interval: 30
          kedaResources:
            interval: 30
          kubernetesResources:
            interval: 30
---
{{- end }}
