apiVersion: v2
type: application
name: external-scaler-azure-cosmos-db
description: Event-based autoscaler for Azure Cosmos DB change feed consumer applications

# Specify the Kubernetes version range that we support.
# We allow pre-release versions for cloud-specific Kubernetes versions such as  v1.21.5-gke.1302 or v1.18.9-eks-d1db3c
kubeVersion: ">=v1.17.0-0"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application and it is recommended to use it with quotes.
appVersion: 0.1.0

home: https://github.com/kedacore/external-scaler-azure-cosmos-db
sources:
  - https://github.com/kedacore/external-scaler-azure-cosmos-db
maintainers:
  - name: Ahmed ElSayed
    email: ahmels@microsoft.com
  - name: Jatin Sanghvi
    email: jasanghv@microsoft.com
  - name: Tom Kerkhove
    email: tomkerkhove@microsoft.com
